# Ganzua doesn't ship pre-built binaries, and only providers lower bounds for dependencies.
# Thus, Python level updates are less important, users can upgrade independently.
# The `just upgrade-deps` script should be used for managing development dependencies + lower bounds.
#
# Dependabot is only used for keeping GH Actions up to date.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"  # update workflows
      - "/.github/actions/*"  # update helper actions
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "pip"
    # We NEVER want pip updates, since we use the manual `just upgrade-deps` workflow.
    # Therefore, we forbid PRs, and also exclude the Corpus from the dependency graph.
    # Docs: https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/configure-version-updates#disabling-dependabot-version-updates
    # Docs: https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#exclude-paths-
    directory: "/"
    schedule:
      interval: "monthly"
    exclude-paths:
      - "corpus/**"
      - "tests/**"
    open-pull-requests-limit: 0
