name: Set up development tools
description: install Python, UV, and Just
inputs:
  python-version:
    required: true
runs:
  using: composite
  steps:
    - uses: taiki-e/install-action@just
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: ${{ inputs.python-version }}
